"""Generate reports/COVERAGE.md from the built records (run after build_index.py)."""
from pathlib import Path
import json, os, sqlite3

ROOT = Path(__file__).resolve().parents[1] / 'outputs' / 'cv_knowledge_base'
R = ROOT / 'records'


def jl(name):
    return [json.loads(l) for l in (R / name).read_text(encoding='utf-8').splitlines() if l.strip()]


topics, tasks, apis, qa = jl('topics.jsonl'), jl('tasks.jsonl'), jl('apis.jsonl'), jl('qa.jsonl')
examples, corrections, pages = jl('manual_examples.jsonl'), jl('corrections.jsonl'), jl('pages.jsonl')
sources = json.loads((R / 'sources.json').read_text(encoding='utf-8'))
sources = sources if isinstance(sources, list) else sources.get('sources', [])
validation = json.loads((ROOT / 'reports' / 'validation.json').read_text(encoding='utf-8'))
supp_path = ROOT / 'reports' / 'supplement_validation.json'
supp = json.loads(supp_path.read_text(encoding='utf-8')) if supp_path.exists() else None

# Terms the user explicitly asked for (2026-10-07 request), mapped by search over topic/API text.
REQUESTED = ['convolution', 'cv2', 'filter', 'kernel', 'depth', 'border types', 'bilateral', 'median blur',
             'Gaussian blur', 'botch filter', 'HOG', 'Local Binary Pattern', 'Sobel', 'SCAR', 'getGaussianKernel',
             'Canny', 'edges histogram', 'R10', 'plot dot bar', 'subplot', 'imread', 'imshow', 'color conversion',
             'masking functions', 'morphological operations', 'dilate', 'distanceTransform', 'markers', 'watershed',
             'clustering', 'kmeans', 'Laplacian', 'convertScaleAbs', 'HoughCircles', 'SIFT_create',
             'detectAndCompute', 'drawKeypoints', 'np.sqrt', 'Hough line transformation']


def find(term):
    t = term.lower()
    hits = [x['id'] for x in topics if any(t == a.lower() for a in x['aliases']) or t in x['title'].lower()]
    if not hits:
        hits = [x['id'] for x in topics if any(t in a.lower() for a in x['aliases'])]
    if not hits:
        hits = [x['id'] for x in apis if t in x['title'].lower()]
    return hits


def size(p):
    return sum(f.stat().st_size for f in Path(p).rglob('*') if f.is_file())


mb = lambda b: f'{b / 1e6:.1f} MB'
core = [t for t in topics if t.get('review_status') == 'curated']
supplement = [t for t in topics if t.get('review_status') == 'curated_supplement_tested']
db = sqlite3.connect(ROOT / 'knowledge.sqlite')
kinds = dict(db.execute('SELECT kind, COUNT(*) FROM records GROUP BY kind').fetchall())
integrity = db.execute('PRAGMA integrity_check').fetchone()[0]
db.close()

out = ['# Coverage, limits and verification', '',
       'Generated by `work/build_coverage.py` from the built records. Counts reflect the files on disk at build time.', '',
       '## Sources', '',
       f'- {len(sources)} supplied PDFs, {len(pages)} physical pages; every page has a rendered image and raw OCR record.',
       '- Missing inputs: Lab 02 Manual and a separate Lab 04 task sheet were not supplied; original exercise images/videos/datasets were not supplied (solutions are validated on synthetic data).', '',
       '| Source | Pages |', '|---|---|']
for s in sources:
    out.append(f"| {s.get('title', s['id'])} | {s.get('pages', '')} |")
out += ['', '## Record counts', '', '| Record type | Count |', '|---|---|',
        f'| Topics (from manuals) | {len(core)} |', f'| Topics (supplemental related CV, tested) | {len(supplement)} |',
        f'| Worked tasks | {len(tasks)} |', f'| Manual example groups | {len(examples)} |',
        f'| API reference entries | {len(apis)} |', f'| Q&A retrieval entries | {len(qa)} |',
        f'| Source corrections | {len(corrections)} |']
out += [f'| SQLite records: {k} | {v} |' for k, v in sorted(kinds.items())]
out += [f'| SQLite integrity | {integrity} |', '']

out += ['## Requested terms', '', 'Each term from the original request and the record(s) that answer it.', '',
        '| Requested term | Records |', '|---|---|']
missing = []
for term in REQUESTED:
    hits = find(term)
    if not hits:
        missing.append(term)
    out.append(f"| {term} | {', '.join(hits[:4]) or '**not covered**'} |")
out += ['', f'Uncovered requested terms: {", ".join(missing) if missing else "none"}.',
        'Interpretations recorded as uncertain in `records/terminology.json`: "botch filter" → box filter, "SCAR" → Scharr, "R10" → ROI.', '']

out += ['## Supplemental related topics', '',
        'Added beyond the manuals so later planning/prediction stages cover common OpenCV workflows. Every code fragment is executed by `work/test_supplement.py`.', '']
out += [f"- `{t['id']}` — {t['title']}" for t in supplement]
if supp:
    out += ['', f"Supplement validation: **{supp['status']}**, {supp['topics'] - supp['failed']}/{supp['topics']} snippets passed (OpenCV {supp['opencv']}, synthetic image)."]
tv_path = ROOT / 'reports' / 'topic_validation.json'
se_path = ROOT / 'reports' / 'search_eval.json'
if tv_path.exists():
    tv = json.loads(tv_path.read_text(encoding='utf-8'))
    out += ['', f"All topics: **{tv['status']}**, {tv['executed'] - tv['failed']}/{tv['executed']} code fragments run with their recorded `setup` (no code: {', '.join(tv['no_code']) or 'none'})."]
if se_path.exists():
    se = json.loads(se_path.read_text(encoding='utf-8'))
    out += ['', '## Search quality', '', '| Query set | Top-1 | Top-3 |', '|---|---|---|']
    for name in ('tuned', 'heldout'):
        r = se[name]
        out.append(f"| {name} ({r['cases']} queries) | {r['top1']}/{r['cases']} | {r['top3']}/{r['cases']} |")
    out += ['', se['note']]
mcq_path = ROOT / 'reports' / 'mcq_eval.json'
facts_path = R / 'facts.jsonl'
if facts_path.exists():
    from collections import Counter
    fc = Counter(json.loads(l)['source_refs'][0].split(':')[0] for l in facts_path.read_text(encoding='utf-8').splitlines() if l.strip())
    out += ['', '## Manual facts', '', f"{sum(fc.values())} atomic facts restated from the manuals (for exam-style questions):", '',
            '| Manual | Facts |', '|---|---|'] + [f'| {k} | {v} |' for k, v in sorted(fc.items())]
if mcq_path.exists():
    mq = json.loads(mcq_path.read_text(encoding='utf-8'))
    out += ['', '## Multiple-choice answering', '', '| Question set | Correct | Note |', '|---|---|---|']
    out += [f"| {k} | {v['correct']}/{v['questions']} | {v['note']} |" for k, v in mq.items()]
out += ['', '## Verification', '',
        f"- Worked tasks: **{validation['status']}**, {len(validation['checks'])} checks, {len(validation['tasks_exercised'])} tasks exercised "
        f"(Python {validation['versions']['python']}, OpenCV {validation['versions']['opencv']}, NumPy {validation['versions']['numpy']}, Matplotlib {validation['versions']['matplotlib']}).",
        '- Data: synthetic fixtures only. No real-data accuracy is claimed.',
        '- OpenCV 5.0 lacked `HOGDescriptor` in a preliminary test, so the reference environment is pinned to 4.13.', '']

out += ['## Size', '', '| Part | Size |', '|---|---|']
for label, p in [('Whole knowledge base folder', ROOT), ('Original PDFs (sources/)', ROOT / 'sources'),
                 ('Page images + OCR (extracted/)', ROOT / 'extracted'), ('Demonstrations (demos/)', ROOT / 'demos'),
                 ('Structured records (records/)', R)]:
    out.append(f'| {label} | {mb(size(p))} |')
out.append(f"| knowledge.sqlite | {mb((ROOT / 'knowledge.sqlite').stat().st_size)} |")
out += ['', 'The planner/predictor only needs `records/` and `knowledge.sqlite` (a few MB); PDFs, page images and demos are provenance and can be excluded from a pip package. Python, OpenCV and NumPy are separate dependencies not counted here.', '',
        '## Known limits', '',
        '- OCR is unproofread; code and equations in scans may contain recognition errors. Curated records are the trusted layer.',
        '- Topic coverage is broad for classical CV but not exhaustive; deep-learning models, weights and training are out of scope beyond `dnn` inference basics.',
        '- Q&A entries are derived from topics and are retrieval examples, not independent evaluation data.',
        '- Supplied course PDFs keep their original ownership; do not redistribute them in a public package.',
        '- No planner, workflow engine or code predictor exists yet; those are the next stages.', '']
(ROOT / 'reports' / 'COVERAGE.md').write_text('\n'.join(out), encoding='utf-8')
print(json.dumps({'requested_terms': len(REQUESTED), 'uncovered': missing, 'topics': len(topics)}))
