"""Lab 03 manual facts: geometric transformations."""

FACTS = [
('lab_03_manual:p3', 'affine', 'A geometric transformation is a mathematical operation that alters the spatial position, orientation, scale or shape of an object without changing its underlying data values.', ''),
('lab_03_manual:p3', 'affine', 'A geometric transformation changes where image information is located, mapping I(x, y) to I(x\', y\').', ''),
('lab_03_manual:p3', 'pixels', 'An image can be viewed as a function I(x, y) where x is the horizontal coordinate, y the vertical coordinate and I the pixel intensity or color.', ''),
('lab_03_manual:p4', 'affine', 'Geometric transformations change where a pixel is located; photometric transformations change what the pixel looks like (color, brightness or contrast).', ''),
('lab_03_manual:p4', 'affine', 'Examples of geometric transformations: affine, linear, rotation, scaling, shearing, perspective transformation and translation.', ''),
('lab_03_manual:p4', 'gamma', 'Examples of photometric (point) transformations: brightness adjustment, contrast enhancement, gamma correction and color conversion.', ''),
('lab_03_manual:p5', 'affine', 'Hierarchy of 2D transformations: linear (rotation, scale, shear) inside affine (adds translation; includes rigid and similarity) inside projective (homography, perspective).', ''),
('lab_03_manual:p6', 'pixels', 'In image coordinates the origin (0,0) is the top-left corner, x increases to the right and y increases downward, unlike Cartesian coordinates.', ''),
('lab_03_manual:p7', 'pixels', 'For a 640x480 image the corner pixels are (0,0), (639,0), (0,479) and (639,479); arrays are indexed image[y, x] while points are written (x, y).', ''),
('lab_03_manual:p7', 'affine', 'A 2D transformation operates on points (x, y) and suits an image plane, photograph, document or planar object.', ''),
('lab_03_manual:p8', 'affine', "OpenCV's warpAffine() accepts a 2x3 matrix while warpPerspective() uses a 3x3 matrix.", ''),
('lab_03_manual:p9', 'coordinates', 'A 3D transformation works on (x, y, z) in 3D world space and uses a 4x4 homogeneous matrix, used in robotics and 3D graphics.', ''),
('lab_03_manual:p9', 'calibration', 'Connecting 3D world coordinates (X, Y, Z) to 2D image coordinates (x, y) involves camera projection and calibration.', ''),
('lab_03_manual:p9', 'coordinates', 'A transformation matrix encodes how to warp, rotate, scale or shear a coordinate space; multiplying a coordinate vector by it gives the new location.', ''),
('lab_03_manual:p9', 'coordinates', 'A 2x2 transformation matrix is read as columns: each column vector is where a basis axis lands after the transformation.', ''),
('lab_03_manual:p10', 'coordinates', 'The first column vector of a 2x2 transformation matrix is the new X-axis (image of the unit vector (1,0)); the second column is the new Y-axis (image of (0,1)).', ''),
('lab_03_manual:p10', 'coordinates', 'In matrix [[a, b], [c, d]], a is horizontal scaling (a negative value flips horizontally) and d is vertical scaling (negative flips vertically).', ''),
('lab_03_manual:p10', 'coordinates', 'In matrix [[a, b], [c, d]], c (Y of the new X-axis) gives vertical shearing and b (X of the new Y-axis) gives horizontal shearing.', ''),
('lab_03_manual:p11', 'coordinates', 'A pure rotation must change all four matrix values together using sine and cosine so both axes stay perpendicular (90 degrees apart).', ''),
('lab_03_manual:p11', 'affine', 'An affine transformation preserves collinearity (points on a line stay on a line) and parallelism (parallel lines stay parallel).', ''),
('lab_03_manual:p11', 'affine', 'An affine transformation can change angles and distances but preserves the ratio of distances between points on a straight line.', ''),
('lab_03_manual:p11', 'affine', "An affine transformation is a linear transformation followed by a translation: p' = Ap + b, where A is the linear matrix and b the translation vector.", ''),
('lab_03_manual:p13', 'affine', 'Shearing turns squares into tilted parallelograms while parallel lines remain parallel.', ''),
('lab_03_manual:p13', 'affine', 'A linear transformation is an affine transformation without a translation vector; it uses only matrix multiplication and is tethered to the origin.', ''),
('lab_03_manual:p13', 'affine', "A linear transformation multiplies a coordinate vector by a 2x2 matrix: p' = Ap, giving x' = ax + by and y' = cx + dy.", ''),
('lab_03_manual:p14', 'affine', 'Scaling multiplies coordinates by scale factors sx and sy on the diagonal of the matrix, so the axes scale independently.', ''),
('lab_03_manual:p14', 'affine', 'Rotation by theta uses the matrix [[cos theta, -sin theta], [sin theta, cos theta]] and turns space around the origin.', ''),
('lab_03_manual:p14', 'affine', 'Reflection flips geometry like a mirror; a negative diagonal value such as [[1, 0], [0, -1]] reflects across the X-axis.', ''),
('lab_03_manual:p15', 'affine', "Horizontal shear adds a fraction k of one coordinate to another: x' = x + ky, with matrix [[1, k], [0, 1]].", ''),
('lab_03_manual:p16', 'affine', 'A 2x2 linear transformation cannot translate: any matrix times the zero vector is zero, so the origin is anchored.', ''),
('lab_03_manual:p17', 'coordinates', 'Homogeneous coordinates add a dummy 1, turning (x, y) into (x, y, 1), so translation can be done by matrix multiplication alone.', ''),
('lab_03_manual:p17', 'coordinates', 'A 3x3 homogeneous matrix holds translation tx and ty in its rightmost column: [[1, 0, tx], [0, 1, ty], [0, 0, 1]].', ''),
('lab_03_manual:p17', 'coordinates', 'The manual says separate vector addition in p\' = Ap + b breaks the GPU matrix-multiplication pipeline, motivating homogeneous coordinates.', 'The reliable benefit is a uniform representation and composition; speed depends on implementation (correction C10).'),
('lab_03_manual:p18', 'coordinates', 'With homogeneous coordinates, scale, rotation and translation matrices can be multiplied into one master matrix and applied in a single multiplication (composition).', ''),
('lab_03_manual:p18', 'perspective', 'Projective transformations (homographies) simulate how cameras perceive 3D depth in 2D; they allow parallel lines to converge, creating perspective.', ''),
('lab_03_manual:p18', 'perspective', 'Affine transformations always preserve parallelism; projective transformations do not.', ''),
('lab_03_manual:p19', 'perspective', 'A projective transformation uses a full 3x3 matrix H; the result is normalized by dividing by the third coordinate w.', ''),
('lab_03_manual:p19', 'perspective', "Projective equations: x' = (h11 x + h12 y + h13) / (h31 x + h32 y + h33) and y' = (h21 x + h22 y + h23) / (h31 x + h32 y + h33).", ''),
('lab_03_manual:p19', 'perspective', 'In an affine transformation the bottom row of the 3x3 matrix is fixed to [0, 0, 1], so the denominator is always 1.', ''),
('lab_03_manual:p19', 'perspective', 'In a projective transformation the denominator varies with x and y; points further away get a larger denominator and shrink together, which generates depth.', ''),
('lab_03_manual:p20', 'perspective', 'Projective transformations model converging lines (a road narrowing at the horizon), camera viewpoint changes and planar alignment.', ''),
('lab_03_manual:p20', 'perspective', 'A rectangular document photographed at an angle appears as a trapezoid; a projective transformation reverses this into a flat rectangle.', ''),
]
