"""Lab 05 manual facts: image segmentation."""

FACTS = [
('lab_05_manual:p3', 'segmentation', 'Image segmentation partitions an image into distinct, non-overlapping regions, each corresponding to a meaningful object or part of the scene.', ''),
('lab_05_manual:p3', 'segmentation', 'Segmentation separates an image into areas sharing similar visual characteristics such as color, texture or intensity.', ''),
('lab_05_manual:p3', 'segmentation', 'Segmentation technique families: region-based, edge detection based and clustering-based segmentation.', ''),
('lab_05_manual:p5', 'threshold', 'In thresholding segmentation a pixel intensity is compared to a predefined threshold: above it belongs to one region (object), otherwise to another (background).', ''),
('lab_05_manual:p5', 'canny', 'Edge-based segmentation identifies rapid intensity changes at object boundaries using Sobel, Canny or Laplacian of Gaussian (LoG).', ''),
('lab_05_manual:p5', 'kmeans', 'Clustering techniques like K-Means or Mean-Shift group similar pixels by feature similarity such as color values.', ''),
('lab_05_manual:p5', 'segmentation', 'In graph-based segmentation pixels are nodes and edges represent pixel similarity; minimum spanning trees or graph cuts partition the image.', ''),
('lab_05_manual:p6', 'segmentation', 'Graph-cut segmentation uses a minimum cut / max flow between a source and a sink, minimizing the cut cost.', ''),
('lab_05_manual:p6', 'segmentation', 'Segmentation in medical imaging isolates anatomical structures or tumors in X-rays, CT scans or MRIs.', ''),
('lab_05_manual:p6', 'segmentation', 'In autonomous vehicles segmentation detects pedestrians, other vehicles and road signs.', ''),
('lab_05_manual:p6', 'segmentation', 'Satellite image segmentation classifies land cover, monitors deforestation and assesses urban growth.', ''),
('lab_05_manual:p6', 'segmentation', 'In biomedical microscopy segmentation counts cells, identifies cell nuclei and helps diagnose diseases.', ''),
('lab_05_manual:p6', 'segmentation', 'In augmented reality segmentation supports scene understanding and real-time object tracking.', ''),
('lab_05_manual:p8', 'threshold', 'Thresholding divides an image into two regions by pixel intensity; it is simple and effective for objects with distinct intensity differences.', ''),
('lab_05_manual:p8', 'threshold', 'Global thresholding applies a single threshold value to the entire image; effective when objects and background have a clear intensity difference.', ''),
('lab_05_manual:p8', 'threshold', 'The global threshold example is cv2.threshold(image, 128, 255, cv2.THRESH_BINARY).', ''),
('lab_05_manual:p8', 'adaptive', 'Adaptive thresholding uses different threshold values for different regions, adapting to local intensity variations; ideal for varying lighting conditions.', ''),
('lab_05_manual:p9', 'adaptive', 'The adaptive example is cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2): block size 11 and constant C = 2.', ''),
('lab_05_manual:p9', 'otsu', "Otsu's thresholding automatically selects an optimal threshold that maximizes the inter-class variance between object and background pixels.", ''),
('lab_05_manual:p9', 'otsu', "Otsu's thresholding is suitable when the pixel intensity distribution is bimodal.", ''),
('lab_05_manual:p9', 'otsu', "Otsu in OpenCV: cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU); the given threshold 0 is ignored.", ''),
('lab_05_manual:p9', 'mask', 'Color-based thresholding thresholds multiple color channels (RGB or HSV) to segment objects with distinct colors.', ''),
('lab_05_manual:p9', 'mask', 'Color thresholding converts to HSV with cv2.cvtColor(image, cv2.COLOR_BGR2HSV) and builds a mask with cv2.inRange(hsv_image, lower_bound, upper_bound).', ''),
('lab_05_manual:p10', 'canny', 'Hysteresis thresholding (Canny) uses two thresholds: a high threshold to detect strong edges and a low threshold to link weak edges; example cv2.Canny(image, 100, 200).', ''),
('lab_05_manual:p10', 'canny', 'Edge detection segmentation detects boundaries by identifying rapid changes in intensity or color; useful for extracting contours and boundaries.', ''),
('lab_05_manual:p10', 'region', 'Region growing starts with a seed pixel and expands to neighboring pixels that are similar by a criterion such as intensity or color.', ''),
('lab_05_manual:p10', 'region', 'Region growing is effective for segmenting regions with uniform characteristics.', ''),
('lab_05_manual:p11', 'region', 'The region growing code uses a stack, adds a pixel when abs(intensity - seed intensity) < threshold (threshold = 50) and pushes its 4 neighbors.', 'The manual code mixes (x, y) with array indexing; use image[y, x] with OpenCV point order (correction C22).'),
('lab_05_manual:p12', 'watershed', 'Watershed segmentation treats the image as a topographic map and simulates flooding to find segment boundaries.', ''),
('lab_05_manual:p12', 'watershed', 'Watershed is suitable for segmenting touching or overlapping objects.', ''),
('lab_05_manual:p12', 'watershed', 'Watershed steps: preprocessing, marker generation, gradient calculation, marker labeling, watershed transformation and post-processing.', ''),
('lab_05_manual:p12', 'watershed', 'Watershed markers can be placed manually, created by thresholding, or created with a distance transform around object centers.', ''),
('lab_05_manual:p12', 'watershed', 'Watershed treats the gradient image as a topographic surface where high gradient values are peaks; basins fill from the labeled markers and meet at boundaries.', ''),
('lab_05_manual:p12', 'watershed', 'Watershed markers are labeled with different integer values; morphological erosion or dilation can refine the result.', ''),
('lab_05_manual:p13', 'watershed', 'The watershed code thresholds with Otsu, removes noise with a morphological opening (5x5 kernel, 2 iterations) and dilates to get the sure background.', ''),
('lab_05_manual:p13', 'distance', 'The watershed code gets the sure foreground by thresholding cv2.distanceTransform(opening, cv2.DIST_L2, 5) at 0.2 * max.', ''),
('lab_05_manual:p13', 'watershed', 'The unknown region is sure background minus sure foreground (cv2.subtract); markers come from cv2.connectedComponents, +1 so background is 1, and unknown set to 0.', ''),
('lab_05_manual:p13', 'watershed', 'After cv2.watershed(image, markers), boundary pixels are labeled -1 and are colored to show the segmentation.', 'In BGR, red is [0, 0, 255]; the manual uses [255, 0, 0] (correction C23).'),
('lab_05_manual:p14', 'kmeans', 'Clustering-based segmentation groups pixels into clusters by feature similarity using K-Means, Mean-Shift or DBSCAN.', ''),
('lab_05_manual:p14', 'kmeans', 'K-means features per pixel are RGB values or LAB/HSV for color images, or intensity for grayscale images.', ''),
('lab_05_manual:p14', 'kmeans', 'K-means initialization chooses the number of clusters K and initializes K centroids randomly or by a heuristic.', ''),
('lab_05_manual:p14', 'kmeans', 'K-means assignment step: assign each pixel to the nearest centroid by Euclidean distance; update step: recompute each centroid as the mean of its pixels.', ''),
('lab_05_manual:p14', 'kmeans', 'K-means repeats assignment and update until convergence, when cluster assignments no longer change significantly; each cluster becomes a segment.', ''),
('lab_05_manual:p15', 'kmeans', 'The K-means code reshapes the image to (-1, 3), converts to np.float32, and calls cv2.kmeans(pixel_values, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS) with K = 4.', ''),
('lab_05_manual:p15', 'kmeans', 'K-means criteria combine cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER (100 iterations, epsilon 0.2); centers are converted back with np.uint8.', ''),
('lab_05_manual:p15', 'kmeans', 'The segmented K-means image is centers[labels.flatten()] reshaped back to the original image shape.', ''),
('lab_05_manual:p15', 'segmentation', 'Deep learning-based segmentation uses CNNs for semantic and instance segmentation; suitable for complex tasks and large datasets.', ''),
('lab_05_manual:p16', 'segmentation', 'TensorFlow, PyTorch and Keras provide pre-trained models for deep learning-based segmentation.', ''),
('lab_05_manual:p16', 'segmentation', 'Active contour models (snakes) are deformable models that evolve to object boundaries using image gradients and constraints; used for object tracking and boundary refinement.', ''),
]
