"""OpenCV parameter meanings and computer-vision fundamentals beyond the manuals.

Written from the OpenCV 4.x reference documentation and standard CV textbooks;
source ref 'opencv_docs:<function>' or 'cv_fundamentals:<topic>'. Values that can be
read from the library (constants, defaults) live in facts_introspect.py instead.

FACTS: (ref, topic, statement, note)
TRIPLES: (subject aliases, attribute, value, ref) -- one property per row, so a question
about one subject cannot be answered with another subject's value.
"""

D = 'opencv_docs:'
F = 'cv_fundamentals:'

FACTS = [
# ---- reading, colour, display
(D + 'imread', 'io', 'cv2.imread(filename, flags) reads an image; flags default to cv2.IMREAD_COLOR (3-channel BGR). IMREAD_GRAYSCALE loads single-channel, IMREAD_UNCHANGED keeps alpha.', ''),
(D + 'cvtColor', 'colors', 'cv2.cvtColor(src, code) converts colour spaces; cv2.COLOR_BGR2RGB converts OpenCV BGR to RGB for Matplotlib, COLOR_BGR2HSV converts to HSV and COLOR_BGR2GRAY to grayscale.', ''),
(D + 'cvtColor', 'colors', 'Matplotlib expects images in RGB order, while OpenCV stores colour images in BGR order.', ''),
(D + 'cvtColor', 'colors', 'In 8-bit HSV in OpenCV, hue ranges 0-179 and saturation and value range 0-255.', ''),
# ---- smoothing
(D + 'GaussianBlur', 'gaussian', 'cv2.GaussianBlur(src, ksize, sigmaX, sigmaY=0): ksize width and height must be positive and odd.', ''),
(D + 'GaussianBlur', 'gaussian', 'In cv2.GaussianBlur, if sigmaY is 0 it is set equal to sigmaX; if both are 0 they are computed from the kernel size.', ''),
(D + 'blur', 'box', 'cv2.blur(src, ksize) is the normalized box filter (mean of the neighbourhood); cv2.boxFilter can skip normalization.', ''),
(D + 'medianBlur', 'median', 'cv2.medianBlur(src, ksize) replaces each pixel with the neighbourhood median; ksize must be odd and greater than 1; best for salt-and-pepper noise.', ''),
(D + 'bilateralFilter', 'bilateral', 'cv2.bilateralFilter(src, d, sigmaColor, sigmaSpace) smooths while preserving edges by weighting both spatial distance and intensity difference.', ''),
# ---- derivatives
(D + 'Sobel', 'gradients', 'cv2.Sobel(src, ddepth, dx, dy, ksize=3): dx and dy are the derivative orders; ksize is the size of the extended Sobel kernel (1, 3, 5 or 7).', ''),
(D + 'Sobel', 'gradients', 'cv2.Sobel with dx=1, dy=0 computes the horizontal gradient Gx (derivative along x), which responds to vertical edges.', ''),
(D + 'Sobel', 'gradients', 'cv2.Sobel with dx=0, dy=1 computes the vertical gradient Gy (derivative along y), which responds to horizontal edges.', ''),
(D + 'Sobel', 'gradients', 'cv2.Sobel ksize=3 means a 3x3 Sobel kernel.', ''),
(D + 'Sobel', 'depth', 'A signed float output depth such as cv2.CV_64F keeps negative gradient values that an 8-bit cv2.CV_8U output would clip to 0.', ''),
(D + 'Scharr', 'scharr', 'cv2.Scharr(src, ddepth, dx, dy) computes a 3x3 derivative that is more accurate (rotationally symmetric) than the 3x3 Sobel.', ''),
(D + 'Laplacian', 'laplacian', 'cv2.Laplacian(src, ddepth, ksize=1): the default ksize is 1, which uses the 3x3 aperture [[0,1,0],[1,-4,1],[0,1,0]].', ''),
(D + 'Laplacian', 'laplacian', 'The Laplacian is a second derivative operator; Sobel, Scharr, Prewitt and the Canny gradient step are first derivative operators.', ''),
(D + 'convertScaleAbs', 'convert_abs', 'cv2.convertScaleAbs(src, alpha=1, beta=0) computes saturate(|src*alpha + beta|) and converts the result to 8-bit unsigned (uint8).', ''),
(D + 'convertScaleAbs', 'convert_abs', 'In cv2.convertScaleAbs, alpha is the optional scale factor (contrast) and beta is the delta added to the scaled values (brightness).', ''),
# ---- Canny
(D + 'Canny', 'canny', 'cv2.Canny(image, threshold1, threshold2, apertureSize=3, L2gradient=False): threshold1 and threshold2 are the hysteresis thresholds.', ''),
(D + 'Canny', 'canny', 'In cv2.Canny, apertureSize is the aperture size of the Sobel operator used for the gradient (default 3).', ''),
(D + 'Canny', 'canny', 'In cv2.Canny, L2gradient=True uses the L2 norm sqrt(Gx^2 + Gy^2) for gradient magnitude; the default False uses the L1 norm |Gx| + |Gy|.', ''),
# ---- thresholding
(D + 'threshold', 'threshold', 'cv2.threshold(src, thresh, maxval, type) returns retval and dst; THRESH_BINARY sets pixels above thresh to maxval and others to 0, THRESH_BINARY_INV does the opposite.', ''),
(D + 'threshold', 'otsu', 'Otsu thresholding is requested by combining flags, e.g. cv2.THRESH_BINARY + cv2.THRESH_OTSU or cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU; the thresh argument is ignored and retval is the computed threshold.', ''),
(D + 'threshold', 'threshold', 'THRESH_TRUNC caps values above the threshold at the threshold; THRESH_TOZERO sets values below the threshold to 0.', ''),
(D + 'adaptiveThreshold', 'adaptive', 'cv2.adaptiveThreshold(src, maxValue, adaptiveMethod, thresholdType, blockSize, C): blockSize is the odd neighbourhood size used to compute the local threshold.', ''),
(D + 'adaptiveThreshold', 'adaptive', 'In cv2.adaptiveThreshold, C is a constant subtracted from the local mean or Gaussian-weighted mean; adaptiveMethod is ADAPTIVE_THRESH_MEAN_C or ADAPTIVE_THRESH_GAUSSIAN_C.', ''),
(D + 'inRange', 'mask', 'cv2.inRange(src, lowerb, upperb) returns a binary mask that is 255 where every channel lies within [lowerb, upperb] and 0 elsewhere.', ''),
# ---- morphology
(D + 'morphologyEx', 'morphology', 'Morphological opening (MORPH_OPEN) is erosion followed by dilation; it removes small noise (white specks) while keeping object shape.', ''),
(D + 'morphologyEx', 'morphology', 'Morphological closing (MORPH_CLOSE) is dilation followed by erosion; it fills small holes and gaps inside objects.', ''),
(D + 'morphologyEx', 'morphology_more', 'Morphological gradient is dilation minus erosion (object outline); top-hat is image minus opening; black-hat is closing minus image.', ''),
(D + 'erode', 'morphology', 'Erosion shrinks bright foreground regions and removes small specks; dilation grows bright regions and fills small gaps.', ''),
(D + 'distanceTransform', 'distance', 'cv2.distanceTransform(src, distanceType, maskSize) gives each foreground pixel its distance to the nearest zero pixel; DIST_L2 is Euclidean, DIST_L1 city-block, DIST_C chessboard.', ''),
(D + 'connectedComponents', 'components', 'cv2.connectedComponents labels connected foreground regions with integers; label 0 is the background.', ''),
(D + 'watershed', 'watershed', 'cv2.watershed(image, markers) needs an 8-bit 3-channel image and int32 markers; it modifies markers in place and marks boundary pixels with -1.', ''),
(D + 'watershed', 'watershed', 'Before cv2.watershed, markers are incremented by 1 so the sure background becomes 1 instead of 0, and the unknown region is set to 0 so watershed decides it.', ''),
# ---- k-means
(D + 'kmeans', 'kmeans', 'cv2.kmeans(data, K, bestLabels, criteria, attempts, flags): data must be float32 with one row per sample; attempts is the number of runs with different initial centers.', ''),
(D + 'kmeans', 'kmeans', 'cv2.KMEANS_RANDOM_CENTERS picks random initial centers; cv2.KMEANS_PP_CENTERS uses the kmeans++ initialization.', ''),
# ---- Hough
(D + 'HoughLines', 'hough', 'cv2.HoughLines(image, rho, theta, threshold): rho is the distance resolution of the accumulator in pixels, theta the angle resolution in radians, threshold the minimum accumulator votes.', ''),
(D + 'HoughLines', 'hough', 'cv2.HoughLines returns lines as (rho, theta) in the polar form rho = x cos(theta) + y sin(theta).', ''),
(D + 'HoughLinesP', 'hough', 'cv2.HoughLinesP is the probabilistic Hough transform returning segment endpoints; minLineLength rejects shorter segments and maxLineGap joins segments with smaller gaps.', ''),
(D + 'HoughCircles', 'circles', 'cv2.HoughCircles(image, method, dp, minDist, param1, param2, minRadius, maxRadius) implements the cv2.HOUGH_GRADIENT method (and HOUGH_GRADIENT_ALT).', ''),
(D + 'HoughCircles', 'circles', 'In cv2.HoughCircles, dp is the inverse ratio of accumulator resolution to image resolution and minDist is the minimum distance between the centers of detected circles.', ''),
(D + 'HoughCircles', 'circles', 'In cv2.HoughCircles with HOUGH_GRADIENT, param1 is the higher threshold passed to the Canny edge detector and param2 is the accumulator threshold for circle centers (smaller gives more false circles).', ''),
(D + 'HoughCircles', 'circles', 'In cv2.HoughCircles, minRadius and maxRadius bound the circle radius.', ''),
# ---- features
(D + 'SIFT_create', 'sift', 'In cv2.SIFT_create, nOctaveLayers is the number of layers per octave, contrastThreshold filters weak low-contrast features, edgeThreshold filters edge-like features and sigma is the Gaussian sigma of the first octave.', ''),
(D + 'drawKeypoints', 'sift', 'cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS draws each keypoint as a circle showing its size and orientation; the default flag draws only centers.', ''),
(D + 'detectAndCompute', 'sift', 'sift.detect finds keypoints only, sift.compute computes descriptors for given keypoints, and sift.detectAndCompute does both in one call.', ''),
(D + 'BFMatcher', 'matching', 'cv2.BFMatcher(normType, crossCheck): use NORM_L2 for float descriptors like SIFT and NORM_HAMMING for binary descriptors like ORB.', ''),
(D + 'findHomography', 'ransac', 'cv2.findHomography(src, dst, cv2.RANSAC, ransacReprojThreshold) estimates a 3x3 homography and returns an inlier mask.', ''),
# ---- geometry
(D + 'warpAffine', 'affine', 'cv2.warpAffine takes a 2x3 matrix; cv2.warpPerspective takes a 3x3 matrix.', ''),
(D + 'getAffineTransform', 'affine', 'cv2.getAffineTransform needs 3 point pairs; cv2.getPerspectiveTransform needs 4 point pairs.', ''),
(D + 'resize', 'resize', 'cv2.resize(src, dsize, fx, fy, interpolation): dsize is (width, height); fx and fy are scale factors along x and y used when dsize is None.', ''),
# ---- fundamentals
(F + 'segmentation', 'segmentation', 'Semantic segmentation gives every pixel of the same class the same label; instance segmentation also separates different instances (objects) of the same class.', ''),
(F + 'segmentation', 'segmentation', 'Panoptic segmentation combines semantic labels for stuff with instance labels for things.', ''),
(F + 'connectivity', 'region', '4-connectivity uses the up, down, left and right neighbours; 8-connectivity also includes the 4 diagonal neighbours.', ''),
(F + 'otsu', 'otsu', "Otsu's method maximizes the between-class (inter-class) variance, equivalently minimizing the within-class (intra-class) variance.", ''),
(F + 'derivatives', 'gradients', 'First derivative edge detectors find edges at gradient magnitude peaks; second derivative detectors (Laplacian, LoG) find edges at zero-crossings.', ''),
(F + 'canny', 'canny', 'The Canny steps in order are Gaussian smoothing, gradient calculation, non-maximum suppression, then hysteresis thresholding.', ''),
(F + 'sift', 'sift', 'SIFT keypoints are invariant to scale and rotation and partially robust to illumination and viewpoint changes.', ''),
(F + 'sift', 'sift', 'The SIFT descriptor uses a 4x4 grid of sub-regions with 8 orientation bins each, giving 4 x 4 x 8 = 128 values.', ''),
(F + 'sift', 'sift', 'SIFT was proposed by David Lowe (1999, 2004).', ''),
(F + 'features', 'features', 'Scale-invariant feature detectors include SIFT, SURF and ORB (via image pyramids); Sobel, Canny and Hough are not scale-invariant feature detectors.', ''),
(F + 'hough', 'hough', 'In the slope-intercept Hough form a line y = mx + b maps to a point (m, b); vertical lines have infinite slope, so the polar (rho, theta) form is used in practice.', ''),
(F + 'kernel', 'kernel', 'Gaussian blur weights neighbours by a Gaussian; box blur weights them equally; median takes the middle value; bilateral also weights by intensity similarity.', ''),
(F + 'histogram', 'histogram', 'A bimodal histogram has two separated peaks (object and background), the case where a single global or Otsu threshold works well.', ''),
(F + 'wavelets', 'wavelets', 'The Fourier transform gives frequency content only; wavelets give joint time (space) and frequency localization.', ''),
]

TRIPLES = [
# manual binding facts: one subject, one property, one value
(['a'], 'controls in matrix [[a, b], [c, d]]', 'horizontal scaling', 'lab_03_manual:p10'),
(['b'], 'controls in matrix [[a, b], [c, d]]', 'horizontal shearing', 'lab_03_manual:p10'),
(['c'], 'controls in matrix [[a, b], [c, d]]', 'vertical shearing', 'lab_03_manual:p10'),
(['d'], 'controls in matrix [[a, b], [c, d]]', 'vertical scaling', 'lab_03_manual:p10'),
(['first column'], 'represents in 2x2 transformation matrix', 'new landing spot for the X-axis', 'lab_03_manual:p10'),
(['second column'], 'represents in 2x2 transformation matrix', 'new landing spot for the Y-axis', 'lab_03_manual:p10'),
(['M'], 'represents in digital image', 'total rows / height', 'lab_01_manual:p10'),
(['N'], 'represents in digital image', 'total columns / width', 'lab_01_manual:p10'),
(['x', 'x-axis'], 'direction in image coordinates, goes, increases', 'right', 'lab_03_manual:p6'),
(['y', 'y-axis'], 'direction in image coordinates, goes, increases', 'down', 'lab_03_manual:p6'),
(['origin'], 'location in image coordinates', 'top-left', 'lab_03_manual:p6'),
(['warpAffine'], 'matrix size, accepts, uses', '2x3', 'lab_03_manual:p8'),
(['warpPerspective'], 'matrix size, uses', '3x3', 'lab_03_manual:p8'),
(['projective transformation', 'homography'], 'matrix size, uses', '3x3', 'lab_03_manual:p19'),
(['3D homogeneous transformation', '3D transformation'], 'matrix size, uses', '4x4', 'lab_03_manual:p9'),
(['2D affine transformation'], 'represented as', '2x3 or 3x3 homogeneous', 'lab_03_manual:p9'),
(['linear transformation'], 'equation, represented by', "p' = Ap", 'lab_03_manual:p13'),
(['affine transformation'], 'equation', "p' = Ap + b", 'lab_03_manual:p11'),
(['linear transformation', 'linear transformations'], 'can achieve', 'scaling, rotation, reflection, shearing', 'lab_03_manual:p14'),
(['linear transformation'], 'limitation', 'cannot translate because origin is anchored', 'lab_03_manual:p16'),
(['homogeneous coordinates'], 'add value', '1', 'lab_03_manual:p17'),
(['homogeneous 3x3 matrix', 'translation values'], 'translation placed in', 'the rightmost column', 'lab_03_manual:p17'),
(['affine transformation'], 'bottom row of the matrix', '[0, 0, 1]', 'lab_03_manual:p19'),
(['projective transformation'], 'also called', 'homography', 'lab_03_manual:p18'),
(['geometric transformation'], 'formula', "(x,y) -> (x',y')", 'lab_03_manual:p4'),
(['photometric transformation'], 'formula', "I(x,y) -> I'(x',y')", 'lab_03_manual:p4'),
(['geometric transformation'], 'example', 'rotation, scaling, shearing, translation, affine, perspective', 'lab_03_manual:p4'),
(['photometric transformation'], 'example', 'brightness adjustment, contrast enhancement, gamma correction, color conversion', 'lab_03_manual:p4'),
(['Matplotlib'], 'expects image format', 'RGB', 'lab_01_manual:p14'),
(['OpenCV'], 'loads color images in format by default', 'BGR', 'lab_01_manual:p14'),
(['OpenCV'], 'mainly used for', 'general computer vision tasks', 'lab_01_manual:p7'),
(['fx', 'fy'], 'represent in cv2.resize', 'scale factors along x and y', 'lab_01_manual:p16'),
(['reshape(-1, 3)'], 'converts', '3D image array to 2D array', 'lab_01_manual:p20'),
(['Gx'], 'detects edges', 'vertical edges', 'lab_manual_06:p7'),
(['Gy'], 'detects edges', 'horizontal edges', 'lab_manual_06:p7'),
(['dx=1, dy=0'], 'computes in cv2.Sobel', 'horizontal gradient (Gx)', D + 'Sobel'),
(['dx=0, dy=1'], 'computes in cv2.Sobel', 'vertical gradient (Gy)', D + 'Sobel'),
(['Sobel', 'Canny/Sobel', 'Canny'], 'derivative', 'first derivative', F + 'derivatives'),
(['Laplacian', 'LoG'], 'derivative', 'second derivative', F + 'derivatives'),
(['threshold1'], 'in cv2.Canny is', 'low threshold', 'lab_04_manual:p23'),
(['threshold2'], 'in cv2.Canny is', 'high threshold', 'lab_04_manual:p23'),
(['high threshold'], 'in Canny used to', 'detect strong edges', 'lab_05_manual:p10'),
(['low threshold'], 'in Canny used to', 'link weak edges', 'lab_05_manual:p10'),
(['apertureSize'], 'controls in cv2.Canny', 'Sobel operator aperture size', D + 'Canny'),
(['L2gradient=True', 'L2gradient'], 'norm used', 'L2 norm', D + 'Canny'),
(['sigmaY=0', 'sigmaY'], 'in cv2.GaussianBlur when 0', 'set equal to sigmaX', D + 'GaussianBlur'),
(['cv2.Laplacian', 'Laplacian'], 'default ksize', '1', D + 'Laplacian'),
(['alpha'], 'controls in cv2.convertScaleAbs', 'scale factor (contrast)', D + 'convertScaleAbs'),
(['beta'], 'controls in cv2.convertScaleAbs', 'delta (brightness)', D + 'convertScaleAbs'),
(['rho'], 'represents in cv2.HoughLines', 'distance resolution in pixels', D + 'HoughLines'),
(['theta'], 'represents in cv2.HoughLines', 'angle resolution in radians', D + 'HoughLines'),
(['threshold'], 'represents in cv2.HoughLines', 'accumulator threshold', D + 'HoughLines'),
(['minDist'], 'represents in cv2.HoughCircles', 'minimum distance between centers of detected circles', D + 'HoughCircles'),
(['param1'], 'represents in cv2.HoughCircles', 'higher threshold for Canny', D + 'HoughCircles'),
(['param2'], 'represents in cv2.HoughCircles', 'accumulator threshold for circle centers', D + 'HoughCircles'),
(['cv2.HoughCircles', 'HoughCircles'], 'method implemented', 'cv2.HOUGH_GRADIENT', D + 'HoughCircles'),
(['blockSize'], 'parameter in cv2.adaptiveThreshold', 'neighborhood size', D + 'adaptiveThreshold'),
(['C'], 'parameter in cv2.adaptiveThreshold', 'constant subtracted from the mean', D + 'adaptiveThreshold'),
(['MORPH_OPEN', 'opening'], 'performs', 'erosion then dilation', D + 'morphologyEx'),
(['MORPH_CLOSE', 'closing'], 'performs', 'dilation then erosion', D + 'morphologyEx'),
(['opening', 'morphological opening'], 'removes', 'noise', D + 'morphologyEx'),
(['cv2.watershed', 'watershed'], 'marks boundaries as', '-1', D + 'watershed'),
(['cv2.inRange', 'inRange'], 'parameters', 'src, lowerb, upperb', D + 'inRange'),
(['cv2.Canny', 'Canny()'], 'parameters', 'image, threshold1, threshold2', D + 'Canny'),
(['sift.detectAndCompute', 'detectAndCompute'], 'detects keypoints and computes descriptors', 'sift.detectAndCompute()', D + 'detectAndCompute'),
(['DRAW_RICH_KEYPOINTS', 'drawKeypoints'], 'draws keypoints with size and orientation', 'cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS', D + 'drawKeypoints'),
(['semantic segmentation'], 'means', 'same class gets same label', F + 'segmentation'),
(['instance segmentation'], 'means', 'different instances of same class are separated', F + 'segmentation'),
(['Otsu', "Otsu's thresholding"], 'maximizes', 'inter-class variance', 'lab_05_manual:p9'),
(['Otsu'], 'suitable distribution', 'bimodal', 'lab_05_manual:p9'),
(['region growing'], 'neighbours added in the manual code', '4-connected', 'lab_05_manual:p11'),
(['region growing'], 'seed point in the manual code', '(10,10)', 'lab_05_manual:p10'),
(['region growing'], 'threshold value in the manual code', '50', 'lab_05_manual:p11'),
(['region growing'], 'mask dtype in the manual code', 'np.uint8', 'lab_05_manual:p11'),
(['sure_bg'], 'created by in watershed code', 'dilation', 'lab_05_manual:p13'),
(['sure_fg'], 'threshold in watershed code', '0.2 * max', 'lab_05_manual:p13'),
(['unknown region'], 'calculated as in watershed code', 'subtract(sure_bg, sure_fg)', 'lab_05_manual:p13'),
(['unknown region'], 'set to in watershed code', '0', 'lab_05_manual:p13'),
(['markers'], 'incremented by after connectedComponents', '1', 'lab_05_manual:p13'),
(['K', 'K value'], 'in K-Means code', '4', 'lab_05_manual:p15'),
(['pixel_values'], 'reshaped to in K-Means code', '(-1, 3)', 'lab_05_manual:p15'),
(['pixel_values'], 'converted to in K-Means code', 'np.float32', 'lab_05_manual:p15'),
(['centers'], 'converted to in K-Means code', 'np.uint8', 'lab_05_manual:p15'),
(['SIFT keypoint', 'candidate keypoint'], 'compared with neighbors', '26', 'lab_manual_06:p19'),
(['26 neighbors'], 'consist of', '8 same layer, 9 above, 9 below', 'lab_manual_06:p19'),
(['SIFT descriptor'], 'generated from', '4x4 sub-regions and 8 orientation bins', F + 'sift'),
(['orientation assignment'], 'makes keypoints invariant to', 'rotation', 'lab_manual_06:p20'),
(['keypoint localization'], 'refines location by fitting', '3D quadratic function', 'lab_manual_06:p19'),
(['Hough line', 'Hough line detection'], 'parameter space axes', 'm and b', 'lab_manual_06:p17'),
(['circle Hough', 'circle detection'], 'parameters', 'a, b, and r', 'lab_manual_06:p18'),
(['circle detection'], 'parameter space dimensions', '3', 'lab_manual_06:p18'),
(['Hough Transform'], 'introduced in', '1962', 'lab_manual_06:p17'),
(['Hough Transform'], 'introduced by', 'Paul Hough', 'lab_manual_06:p17'),
(['Canny'], 'developed in', '1986', 'lab_04_manual:p21'),
(['Canny'], 'developed by', 'John F. Canny', 'lab_04_manual:p21'),
(['WPT', 'Wavelet Packet Transform'], 'extension of', 'DWT', 'lab_manual_06:p4'),
(['Morlet'], 'used for', 'oscillatory components', 'lab_manual_06:p3'),
(['Inverse Wavelet Transform'], 'crucial for', 'image reconstruction', 'lab_manual_06:p4'),
]
