"""Lab Manual 06 facts: wavelets, boundary detection, Hough transform, SIFT."""

FACTS = [
('lab_manual_06:p1', 'wavelets', 'Lab Manual 06 covers wavelets, boundary detection, the Hough transform and SIFT (its cover page is labeled Lab 05).', ''),
('lab_manual_06:p3', 'wavelets', 'Wavelet transformation analyzes a signal or image in terms of its frequency components at different scales.', ''),
('lab_manual_06:p3', 'wavelets', 'Wavelet transforms provide time-frequency analysis, particularly useful for non-stationary signals.', ''),
('lab_manual_06:p3', 'wavelets', 'The most common wavelet transforms are the Continuous Wavelet Transform (CWT) and the Discrete Wavelet Transform (DWT).', ''),
('lab_manual_06:p3', 'wavelets', 'The CWT uses continuous wavelet functions (psi) that are dilated (scaled) and translated across the signal.', ''),
('lab_manual_06:p3', 'wavelets', 'The Morlet wavelet is used with the CWT for analyzing oscillatory components in signals.', ''),
('lab_manual_06:p3', 'wavelets', 'CWT is used for time-frequency analysis of continuous signals, such as seismic signal analysis and image analysis.', ''),
('lab_manual_06:p3', 'wavelets', 'The DWT scales and shifts discrete wavelet functions across discrete signal data.', ''),
('lab_manual_06:p3', 'wavelets', 'DWT wavelet families include Daubechies, Haar and Symlet wavelets.', ''),
('lab_manual_06:p3', 'wavelets', 'DWT is widely used in image compression, image denoising and feature extraction, and in signal compression and analysis.', ''),
('lab_manual_06:p4', 'wavelets', 'The Wavelet Packet Transform (WPT) extends the DWT for more flexible decomposition of signals into multiple subbands.', ''),
('lab_manual_06:p4', 'wavelets', 'WPT is used for signals with complex frequency content and for feature extraction in machine learning.', ''),
('lab_manual_06:p4', 'wavelets', 'The inverse wavelet transform reconstructs a signal or image from its wavelet coefficients; it is crucial for compression and denoising.', ''),
('lab_manual_06:p5', 'canny', 'Boundary detection, often called edge detection, identifies object boundaries: significant changes in intensity or color.', ''),
('lab_manual_06:p5', 'canny', 'Edges contain important information about shapes and structures, letting algorithms focus on key regions.', ''),
('lab_manual_06:p6', 'gradients', 'Sobel edge detection is a basic gradient-based method convolving two 3x3 kernels for horizontal and vertical gradients.', ''),
('lab_manual_06:p6', 'gradients', 'In Sobel, the gradient magnitude represents edge strength and the gradient direction indicates edge orientation.', ''),
('lab_manual_06:p7', 'gradients', 'The Sobel Gx kernel measures horizontal change and detects vertical edges; the Gy kernel measures vertical change and detects horizontal edges.', ''),
('lab_manual_06:p7', 'gradients', 'Sobel gives a large response on an edge and zero response in a uniform area; it is a directional difference operation.', ''),
('lab_manual_06:p8', 'depth', 'Sobel uses 64-bit floats (cv2.CV_64F) to preserve negative values, which indicate the direction of intensity change.', ''),
('lab_manual_06:p8', 'gradients', 'Sobel total gradient magnitude G = sqrt(Gx^2 + Gy^2) combines horizontal and vertical changes.', ''),
('lab_manual_06:p10', 'gradients', 'The Sobel magnitude is converted for display with np.uint8(np.clip(magnitude, 0, 255)).', ''),
('lab_manual_06:p11', 'canny', 'Canny edge detection steps: Gaussian smoothing reduces noise, gradient calculation finds magnitude and direction, non-maximum suppression, and hysteresis thresholding.', ''),
('lab_manual_06:p11', 'canny', 'The manual says non-maximum suppression eliminates weak edge pixels and hysteresis tracks edges by linking strong edge pixels.', 'NMS keeps local maxima along the gradient direction (thinning); hysteresis keeps weak pixels connected to strong ones (correction C21).'),
('lab_manual_06:p11', 'canny', 'The Canny detector is known for high accuracy and for detecting thin and continuous edges.', ''),
('lab_manual_06:p12', 'canny', 'Gaussian smoothing in Canny reduces noise to prevent false edges; non-maximum suppression thins thick edges to one-pixel-wide lines.', ''),
('lab_manual_06:p12', 'canny', 'Sobel alone is susceptible to noise and gives thick edges; Canny is a robust multi-stage pipeline giving thin edges.', ''),
('lab_manual_06:p13', 'canny', 'The Canny example blurs with cv2.GaussianBlur(gray, (5, 5), 1.4) then calls cv2.Canny(blurred, 50, 150): 50 lower threshold, 150 upper threshold.', ''),
('lab_manual_06:p14', 'laplacian', 'The LoG operator first applies Gaussian smoothing and then computes the Laplacian; zero-crossings of the result indicate edges.', ''),
('lab_manual_06:p14', 'laplacian', 'LoG is effective at detecting edges with varying scales.', ''),
('lab_manual_06:p15', 'laplacian', 'First derivative (gradient, Canny/Sobel) peaks give edge strength; the second derivative (Laplacian) zero-crossing gives edge location.', ''),
('lab_manual_06:p15', 'convert_abs', 'The LoG code uses cv2.Laplacian(blurred, cv2.CV_64F) and cv2.convertScaleAbs to take absolute values for visualization.', 'Absolute values show response strength; edges are the signed zero-crossings (correction C25).'),
('lab_manual_06:p17', 'hough', 'The Hough transform detects simple shapes within an image, most commonly lines and circles.', ''),
('lab_manual_06:p17', 'hough', 'The Hough transform was introduced by Paul Hough in 1962 for detecting lines in binary images, later extended to circles and ellipses.', ''),
('lab_manual_06:p17', 'hough', 'The Hough transform maps the image spatial domain into a parameter space where each pixel corresponds to a curve or point.', ''),
('lab_manual_06:p17', 'hough', 'For line detection the manual represents a line as y = mx + b, with slope m and y-intercept b as parameter space axes.', 'OpenCV uses the polar form rho = x cos(theta) + y sin(theta), which handles vertical lines (correction C26).'),
('lab_manual_06:p17', 'hough', 'Hough voting: for each edge pixel (typically from Canny) increment every parameter cell of lines passing through it.', ''),
('lab_manual_06:p17', 'hough', 'Hough peak detection: peaks in the parameter space (accumulator) represent lines; back-transformation maps them to image positions.', ''),
('lab_manual_06:p18', 'circles', 'Hough circle detection represents a circle as (x - a)^2 + (y - b)^2 = r^2 with center (a, b) and radius r.', ''),
('lab_manual_06:p18', 'circles', 'The Hough circle parameter space has three dimensions: a, b and r.', ''),
('lab_manual_06:p18', 'circles', 'Hough circle voting picks potential centers and radii from edge pixels; peaks give circle centers and radii.', ''),
('lab_manual_06:p18', 'sift', 'SIFT (Scale-Invariant Feature Transform) extracts and matches features; useful for object recognition, image stitching and tracking.', ''),
('lab_manual_06:p18', 'sift', 'SIFT step 1, scale-space extrema detection, finds keypoint candidates at multiple scales using a Difference of Gaussians (DoG).', ''),
('lab_manual_06:p18', 'sift', 'The Difference of Gaussians (DoG) subtracts two Gaussian-blurred versions of the image: DoG = L(x, y, k sigma) - L(x, y, sigma).', ''),
('lab_manual_06:p19', 'sift', 'SIFT keypoint localization refines each candidate by fitting a 3D quadratic function to nearby scale-space points.', ''),
('lab_manual_06:p19', 'sift', 'A SIFT keypoint must be a local maximum or minimum compared to its 26 neighbors: 8 in the same scale, 9 in the scale above and 9 below.', ''),
('lab_manual_06:p20', 'sift', 'SIFT orientation assignment gives each keypoint a canonical orientation from the dominant gradient direction, making it invariant to rotation.', ''),
('lab_manual_06:p20', 'sift', 'SIFT descriptor generation builds histograms of gradient orientations in sub-regions around the keypoint and concatenates them.', ''),
('lab_manual_06:p21', 'sift', 'The SIFT descriptor is a 128-dimensional vector (4x4 sub-regions x 8 orientation bins), robust to lighting changes.', 'One figure label says 120-dimensional; the standard descriptor is 128 (correction C27).'),
('lab_manual_06:p21', 'matching', 'SIFT keypoint matching compares descriptors using Euclidean distance or other similarity measures.', ''),
('lab_manual_06:p21', 'ransac', 'Matches contain outliers from lighting, viewpoint changes or noise; RANSAC (Random Sample Consensus) estimates the transformation and rejects outliers.', ''),
('lab_manual_06:p22', 'ransac', 'RANSAC keeps only geometrically consistent matches (inliers).', ''),
('lab_manual_06:p22', 'ransac', 'After outlier rejection, the remaining matches estimate a homography between images, used for image stitching or object recognition.', ''),
('lab_manual_06:p23', 'sift', 'The SIFT code creates the detector with cv2.SIFT_create() and calls sift.detectAndCompute(gray, None), returning keypoints and descriptors.', 'descriptors is None when no keypoints are found (correction C28).'),
('lab_manual_06:p23', 'sift', 'cv2.drawKeypoints(image, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS) draws keypoints with size and orientation.', ''),
('lab_manual_06:p23', 'sift', 'len(keypoints) gives the number of keypoints and descriptors.shape is (number of keypoints, 128).', ''),
]
